import {NextIntlClientProvider} from 'next-intl';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from "antd";
import {getMessages} from 'next-intl/server';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Providers from '../_utils/providers';

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
        <Providers>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#4DAE37",
                  colorLink: "#4DAE37",
                  fontFamily: "var(--font-cabinet)",
                },
                components: { 
                  Segmented: {
                    fontWeightStrong: 900
                }},
              }}
              
            >
          {children}
          </ConfigProvider>
          </AntdRegistry>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
